sudo: true
dist: trusty
language: cpp
cache:
  directories:
    - $HOME/cmake-$CMAKE_VERSION.$CMAKE_PATCH-Linux-x86_64/bin
    - $HOME/cmake-$CMAKE_VERSION.$CMAKE_PATCH-Linux-x86_64/share
    - /tmp/downloads
env:
  global:
    - MAKEFLAGS=-j4
    - URHO3D_ENABLE_ALL=ON
    - URHO3D_DOCS=OFF
    - CMAKE_VERSION=3.4
    - CMAKE_PATCH=3
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libasound2-dev
      - libxrandr-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - python3.6
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  except:
    - /^(.*[^\w])?(appveyor|no-ci)-.+$/
matrix:
  fast_finish: true
  include:
    - &Linux-gcc
      os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - <<: *Linux-gcc
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - BUILD_SHARED_LIBS=ON
        - URHO3D_WITH_MONO=ON
    - &Linux-clang
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - llvm-6.0
            - clang-6.0
            - libclang-6.0
    - <<: *Linux-clang
      env:
        - BUILD_SHARED_LIBS=ON
        - URHO3D_WITH_MONO=ON
    - &MacOS
      os: osx
      osx_image: xcode8.3
      compiler: clang
    - <<: *MacOS
      env:
        - BUILD_SHARED_LIBS=ON
        - URHO3D_WITH_MONO=ON
    - <<: *Linux-gcc
      env:
        - BUILD_SHARED_LIBS=OFF
        - CMAKE_TOOLCHAIN_FILE=CMake/Toolchains/Emscripten.cmake
        - EMSCRIPTEN=1
        - EMSCRIPTEN_WASM=0
  exclude:
    - &MingW
      env:
        - CMAKE_TOOLCHAIN_FILE=CMake/Toolchains/MinGW.cmake
        - CMAKE_SYSTEM_PROCESSOR=x86_64
        - URHO3D_RENDERER=D3D9
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
    - <<: *MingW
      env:
        - BUILD_SHARED_LIBS=ON
        - CMAKE_TOOLCHAIN_FILE=CMake/Toolchains/MinGW.cmake
        - CMAKE_SYSTEM_PROCESSOR=x86_64
        - URHO3D_RENDERER=D3D9

before_install: |
  eval "${MATRIX_EVAL}"
  if [[ $TRAVIS_OS_NAME == 'linux' ]];
  then
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb http://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      sudo apt-get update -qq
  else
      brew update
  fi

install: |
  # Update CMake to minimum required version
  mkdir -p /tmp/downloads
  if [[ $TRAVIS_OS_NAME == 'linux' ]];
  then
      if [[ ! -f /tmp/downloads/cmake.tar.gz ]];
      then
          wget --no-check-certificate https://cmake.org/files/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.$CMAKE_PATCH-Linux-x86_64.tar.gz -O /tmp/downloads/cmake.tar.gz
      fi
      if [[ ! -f $HOME/cmake-$CMAKE_VERSION.$CMAKE_PATCH-Linux-x86_64/bin/cmake ]];
      then
          tar xf /tmp/downloads/cmake.tar.gz -C $HOME && rm /tmp/downloads/cmake.tar.gz
      fi
      export PATH=$HOME/cmake-$CMAKE_VERSION.$CMAKE_PATCH-Linux-x86_64/bin:$PATH
      if [[ "$URHO3D_WITH_MONO" != "" ]];
      then
          sudo apt-get install -y --force-yes mono-devel
      fi
  elif [[ "$URHO3D_WITH_MONO" != "" ]];
  then
      # mono
      if [[ ! -f /tmp/downloads/Mono.pkg ]];
      then
          wget https://download.mono-project.com/archive/5.10.1/macos-10-universal/MonoFramework-MDK-5.10.1.57.macos10.xamarin.universal.pkg -O /tmp/downloads/Mono.pkg
      fi
      sudo installer -pkg /tmp/downloads/Mono.pkg -target /
  fi

before_script: |
  if [[ "$EMSCRIPTEN" != "" ]];
  then
      if [[ ! $EMSCRIPTEN_WASM ]]; then
          export BINARYEN=binaryen-master-64bit;
      fi
      git clone --depth 1 https://github.com/urho3d/emscripten-sdk.git
      emscripten-sdk/emsdk activate --build=Release sdk-master-64bit $BINARYEN
      source emscripten-sdk/emsdk_env.sh
      for compiler in $EMSCRIPTEN/{emcc,em++};
      do
          touch -d "2017-01-01 00:00:00 +0800" $compiler;
      done
      export EXTRA_BUILD_FLAGS='--target 11_Physics'
  fi

script: |
  mkdir build
  cd build

  echo "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}"

  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} ..

  cmake --build . $EXTRA_BUILD_FLAGS
